name: 'Milk Studio!'
favicon: null
layout_spectrum: 0.48465
typography_spectrum: 0.51547
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a0a0a0'
    - '#686560'
    - '#dad7d0'
    - '#df606f'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
